### ISSUE TITLE
of_messagebox

### ISSUE THREAD

**Issue by jojo5791** [OpenSourcePFCLibraries/2021#12] opened 2022-12-09 06:28 UTC
I am using PB2022 with latest PFC set of source. However, i found that the messagebox got chopped off at the bottom. Can anyone here guide me how to solve this problem? Please see picture for details.
![image](https://user-images.githubusercontent.com/70992666/206638906-0edb1d54-daa1-464d-bb99-3e611e2263bd.png)

**Comment by mjl38** [comment] 2022-12-09 08:30
Hi,
Which windows version are you running? 
You can resize the message window in your pfE...pbl so it looks better.
regards

**Comment by jojo5791** [comment] 2022-12-09 08:55
I am running on window 10 pro. 
is it this one? if yes, i just resize . the window resize? or
![image](https://user-images.githubusercontent.com/70992666/206664777-36ccb456-a80b-4830-a7f8-50b647e88de7.png)

**Comment by mjl38** [comment] 2022-12-09 09:23
Hi,
I'm also running on Windows 10, but maybe not using the latest version of PFCs. 
yes that's the window I think. 
There's a of_paintinitialwindow() function in it's ancestor pfc_w_message. It uses a variable:
constant Integer SEPARATOR =50
Lower in the code, it does a:

// Adjust the Height of the window to hide the User Input space.
This.Height = cb_1.Y + cb_1.Height + 100 + SEPARATOR

I'm not sure if maybe that code has changed?

here's the complete code of what I have:
`
//////////////////////////////////////////////////////////////////////////////
//
//	Function:  		of_PaintInitialWindow
//
//	Access:  		protected
//
//	Arguments:		(none)
//
//	Returns:  		integer
//						1 if it succeeds and -1 if it fails.
//	
//	Description:	Test for the validity of the SQLspy service.
//
//////////////////////////////////////////////////////////////////////////////
//
//	Revision History
//
//	Version
//	5.0   Initial version
// 5.0.02 Corrected code to determine longest text line.
// 5.0.02 Handle multiple font sizes.
// 5.0.02 Prevent the upper/left window coordinates from opening outside 
// 	the screen.
//
//////////////////////////////////////////////////////////////////////////////
//
/*
 * Open Source PowerBuilder Foundation Class Libraries
 *
 * Copyright (c) 2004-2017, All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted in accordance with the MIT License

 *
 * https://opensource.org/licenses/MIT
 *
 * ====================================================================
 *
 * This software consists of voluntary contributions made by many
 * individuals and was originally based on software copyright (c) 
 * 1996-2004 Sybase, Inc. http://www.sybase.com.  For more
 * information on the Open Source PowerBuilder Foundation Class
 * Libraries see https://github.com/OpenSourcePFCLibraries
*/
//
//////////////////////////////////////////////////////////////////////////////

Integer	li_titlelen=0
Integer	li_textlen=0
Integer	li_longestlen=0
Integer	li_startpoint=1

constant Integer SEPARATOR =50
Integer 	li_msglinelength
Integer	li_widthmidpoint
Integer	li_msglinecount
Integer	li_msgline
Integer	li_tabcharlen
Integer	li_x, li_y
Long 		ll_counttabs, ll_pos
String 	ls_textline
Window	lw_parent
Constant String TAB='~t'

// Handle multiple font sizes.
of_UpdateFontSize()

// Get the Message Title Length (li_titlelen).
If Not IsNull(this.Title) Then
	li_titlelen = Len(this.Title)
End If

// Get the number of lines on the Message Text
li_msglinecount = mle_message.LineCount()

// Get the longest Message Text Line Length (li_textlen). 
li_tabcharlen = Len(TAB)
For li_msgline = 1 to li_msglinecount
	// Set the starting position on the next line,
	// loop until the cursor is confirmed on the next line.
	mle_message.SelectText(li_startpoint, 0)	
	Do While mle_message.selectedline() < li_msgline
		li_startpoint++
		mle_message.SelectText(li_startpoint, 0)
	LOOP
	
	// Get the text on the Current Line.
	ls_textline = mle_message.TextLine()

	// Set the starting point to the end of the current line or start of next line..
	li_startpoint += Len(ls_textline) + 1

	// Determine the number of occurrences of the Tab Character.
	ll_counttabs = 0
	ll_Pos = Pos(ls_textline, TAB)
	Do While ll_Pos > 0
		ll_counttabs ++
		ll_Pos = Pos(ls_textline, TAB, (ll_Pos + li_tabcharlen))
	Loop

	// Keep only the longest line length.
	li_msglinelength = mle_message.LineLength()+ (ll_counttabs * ii_tabchars)
	If li_msglinelength > li_textlen Then
		li_textlen = li_msglinelength
	End If
Next

// Keep the longest of the Title or Message length.
If li_titlelen > li_textlen Then
	li_longestlen = li_titlelen
Else
	li_longestlen = li_textlen
End If

// If at least one of the RightSide buttons are visible,
// prevent the window from width getting too small.
If (cb_print.Visible Or cb_userinput.Visible) Then
	If li_longestlen < 25 Then
		li_longestlen = 25
	End If
End If

// Depending on the number of BottomSide buttons visible,
// prevent the window width from getting too small.
If cb_1.Visible And cb_2.Visible=False And cb_3.Visible=False Then
	If li_longestlen < 10 Then
		li_longestlen = 10
	End If
ElseIf cb_1.Visible And cb_2.Visible And cb_3.Visible=False Then
	If li_longestlen < 20 Then
		li_longestlen = 20
	End If
Else
	If li_longestlen < 30 Then
		li_longestlen = 30
	End If
End If

// Set the appropriate attributes for the Message MLE.
If li_msglinecount > ii_maxlines Then 
	mle_message.VScrollbar = True
	li_longestlen += 4
End If

// According to the text inside the Message Text, 
// resize the Message control.  (Check for predefined min/max)
If li_msglinecount < 2 Then
	// Prevent BottomSide control from moving up too much.
	li_msglinecount = 2
End If
If li_longestlen > ii_maxlinelen Then
	// Prevent the width from going over the set max.
	li_longestlen = ii_maxlinelen
End If
If li_msglinecount > ii_maxlines Then
	// Prevent the Height from going over the set max.	
	li_msglinecount = ii_maxlines
End If
mle_message.Resize(li_longestlen * ii_charwidth + 50, &
						 li_msglinecount * ii_lineheight)

// Move the Right Hand buttons just to the right of the 
// Message.
cb_print.X = mle_message.X + mle_message.Width + SEPARATOR
cb_userinput.X = mle_message.X + mle_message.Width + SEPARATOR

// Set the width of the window according to the size of
// the Message and the RightSide buttons.
If (cb_print.Visible=False And cb_userinput.Visible=False) Then
	This.Width = mle_message.X + mle_message.Width + SEPARATOR + 30
Else
	This.Width = mle_message.X + mle_message.Width + cb_print.Width + (SEPARATOR *2) + 30
End If

// Move the BottomSide Buttons right under the Message.
cb_1.Y = mle_message.Y + mle_message.Height + SEPARATOR
cb_2.Y = mle_message.Y + mle_message.Height + SEPARATOR
cb_3.Y = mle_message.Y + mle_message.Height + SEPARATOR

// Center the BottomSide Buttton(s).  (if visible, offset some 
//	for the print and userinput buttons.)
If (cb_print.Visible Or cb_userinput.Visible) Then
	li_widthmidpoint = (This.Width - cb_print.Width  ) / 2
Else
	li_widthmidpoint = This.Width / 2
End If
If cb_1.Visible And cb_2.Visible=False And cb_3.Visible=False Then
	cb_1.x = li_widthmidpoint - (cb_1.Width / 2)
ElseIf cb_1.Visible And cb_2.Visible And cb_3.Visible=False Then
	cb_1.x = li_widthmidpoint - (cb_1.Width +20)
	cb_2.x = li_widthmidpoint +20
Else
	cb_1.x = li_widthmidpoint - ((cb_1.Width +20) + (cb_1.width/2))
	cb_2.x = li_widthmidpoint - (cb_2.width/2)
	cb_3.x = li_widthmidpoint + (cb_3.width/2 +20)
End If

// Move, Resize, Hide the UserInput controls.
gb_userinput.Move (mle_message.X, &
						 mle_message.Y + mle_message.Height + cb_1.Height + SEPARATOR)
gb_userinput.Width = mle_message.Width						 
gb_userinput.Visible = False						 
st_userinput.Move (mle_message.X, &
						 gb_userinput.Y + gb_userinput.Height + SEPARATOR)
st_userinput.Visible = False						 
mle_userinput.Move(mle_message.X, &
						 st_userinput.Y + st_userinput.Height + 5)
mle_userinput.Width = mle_message.Width
mle_userinput.Visible = False

// Adjust the Height of the window to hide the User Input space.
This.Height = cb_1.Y + cb_1.Height + 100 + SEPARATOR

// Center the window on the Parent window.
lw_parent = ParentWindow()
If IsValid (lw_parent) Then
	li_x = lw_parent.x + lw_parent.width/2  - This.width/2 - 100
	If li_x < 0 Then li_x = 0
	li_y = lw_parent.y + lw_parent.height/2 - This.height/2 - 100
	If li_y < 0 Then li_y = 0	
	This.Move(li_x, li_y)
End If

Return 1
`
(sorry about the bad format of the inserted code. It doesn't seem to work very well on this GitHub).
See if there are any differences. So what I'm suggesting, is that you paste the code in the function of the w_message window and see if it's any better. 
If you can't figure it out, later, if I have some time I'll have a look at what's in the latest PFC version and compare the two.
regards.

**Comment by mjl38** [comment] 2022-12-09 09:52
I have done a comparison of my pfc version with the pb2021 version and the functions are identical. I have no problems with the size of the message window when running the application...

**Comment by mjl38** [comment] 2022-12-09 09:56
Now that I think of it ... the of_message() function has many different versions. I think that we use the one that shows a real MessageBox() at the end, so I wouldn't suffer the problem you are having.
Have to go ...

**Comment by mjl38** [comment] 2022-12-09 10:45
Ok,
To solve your problem, you have to:
1. copy all the code of pfc_w_message.of_paintInitialWindow() to the descendent object: w_message.of_paintInitialWindow().
2. Find this line of code and add a value of at least 30 - 50. I found that 40 seems to look alright:
// Adjust the Height of the window to hide the User Input space.
//This.Height = cb_1.Y + cb_1.Height + 100 + SEPARATOR
This.Height = cb_1.Y + cb_1.Height + 100 + SEPARATOR + 40

**Comment by mjl38** [comment] 2022-12-09 10:46
When you have it working, let me know how much you had to add (I haven't checked how it looks on the window when the buttons are visible).
Then, when I have some time I'll try to modify the PFC class itself, so the override is no longer needed.
regards,
MiguelL

**Comment by jojo5791** [comment] 2022-12-13 06:58
Hi MigueIL

   It worked now with 40. Thank very much for you kind assistance.
![image](https://user-images.githubusercontent.com/70992666/207247689-b7d452f8-d2e5-455e-b679-b175caf1808e.png)

**Comment by mjl38** [comment] 2022-12-13 09:08
YW, hopefully I'll have to time one of these days and be able to make the change in the PFC class itself.
regards

**Comment by bruce-armstrong** [comment] 2022-12-13 17:57
I’m planning to do a fork for PB 2022, and we can incorporate the change into that version if it is truly unique to that version.

**Comment by mjl38** [comment] 2022-12-13 18:02
Hi Bruce,
yes, that's what I was hoping for. I think the need for this small adjustment has been around for quite some time. Maybe since windows 10 was introduced.
I'll wait with the modification and only do it for PB2022 PFC. The only thing I'm not sure of, is how it will look on windows 11. I don't have any version yet, so I won't be able to test that.
regards,
MiguelL

**Comment by bruce-armstrong** [comment] 2022-12-13 18:05
I’m on Windows 11, I can check it there.

**Comment by mjl38** [comment] 2022-12-13 18:07
Great!

**Comment by mjl38** [comment] 2022-12-13 18:08
That would be great!

**Comment by bruce-armstrong** [comment] 2022-12-28 03:39
Can you attempt the same thing using the PFC Example App and show what you’re getting.  What I’m seeing ( on Windows 11 ) is working fine without any mods:



 

From: JaneD ***@***.***> 
Sent: Thursday, December 8, 2022 10:29 PM
To: OpenSourcePFCLibraries/2021 ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [OpenSourcePFCLibraries/2021] of_messagebox (Issue #12)

 

I am using PB2022 with latest PFC set of source. However, i found that the messagebox got chopped off at the bottom. Can anyone here guide me how to solve this problem? Please see picture for details.
 <https://user-images.githubusercontent.com/70992666/206638906-0edb1d54-daa1-464d-bb99-3e611e2263bd.png>

**Comment by bruce-armstrong** [comment] 2022-12-28 03:50
Actually, I’m not on Windows 11.  I run my development environments in Amazon Workspaces, which is running Window Server 2019 Datacenter ( equivalent to Windows 10).

 

From: ***@***.*** ***@***.***> 
Sent: Tuesday, December 27, 2022 7:40 PM
To: 'OpenSourcePFCLibraries/2021' ***@***.***>; 'OpenSourcePFCLibraries/2021' ***@***.***>
Cc: 'Subscribed' ***@***.***>
Subject: RE: [OpenSourcePFCLibraries/2021] of_messagebox (Issue #12)

 

Can you attempt the same thing using the PFC Example App and show what you’re getting.  What I’m seeing ( on Windows 11 ) is working fine without any mods:



 

From: JaneD ***@***.*** ***@***.***> > 
Sent: Thursday, December 8, 2022 10:29 PM
To: OpenSourcePFCLibraries/2021 ***@***.*** ***@***.***> >
Cc: Subscribed ***@***.*** ***@***.***> >
Subject: [OpenSourcePFCLibraries/2021] of_messagebox (Issue #12)

 

I am using PB2022 with latest PFC set of source. However, i found that the messagebox got chopped off at the bottom. Can anyone here guide me how to solve this problem? Please see picture for details.
 <https://user-images.githubusercontent.com/70992666/206638906-0edb1d54-daa1-464d-bb99-3e611e2263bd.png>

**Comment by mjl38** [comment] 2023-01-04 12:13
The fix has been incorporated in PFC 2022, not in PFC2021.

**Closed as completed by mjl38** 2023-01-04 12:13 UTC

**Comment by jojo5791** [comment] 2023-01-05 01:23
Hi, 

Noted with many thanks. Appreciate it a lot.
    On Wednesday, 4 January 2023 at 08:13:35 pm GMT+8, Miguel ***@***.***> wrote:  
 
 


The fix has been incorporated in PFC 2022, not in PFC2021.
